CREATE TABLE USER_ACCOUNT (
    ID VARCHAR2(255) PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PESEL VARCHAR2(11),
    FIRST_NAME VARCHAR2(255),
    LAST_NAME VARCHAR2(255),
    PHONE_NUMBER NUMBER(9),
    DATE_OF_BIRTH DATE,
    USER_ROLE VARCHAR2(20),
    USER_GENDER VARCHAR2(20),
    HASHED_PASSWORD VARCHAR2(97),
    VERIFIED NUMBER(1) DEFAULT 0
);

CREATE TABLE VERIFICATION_CODE (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    CODE VARCHAR2(6),
    EXPIRY_DATE TIMESTAMP,
    CONSTRAINT FK_VC_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE RESET_PASSWORD_CODE (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    CODE VARCHAR2(6),
    EXPIRY_DATE TIMESTAMP,
    CONSTRAINT FK_RPC_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE LOGIN_ATTEMPTS (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255),
    IP_ADDRESS VARCHAR2(255),
    SUCCESS NUMBER(1),
    ATTEMPT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LA_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE AUDIT_LOG (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255),
    IP_ADDRESS VARCHAR2(255),
    ACTION_NAME VARCHAR2(255),
    LOG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AL_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE BLACK_LIST (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    REASON VARCHAR2(255),
    EXPIRES_AT TIMESTAMP,
    ADMIN_ID VARCHAR2(255),
    CREATION_DATE DATE,
    CONSTRAINT FK_BL_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE REFRESH_TOKEN (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    TOKEN VARCHAR2(255),
    EXPIRY_DATE TIMESTAMP,
    CONSTRAINT FK_RT_USER FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(ID)
);

CREATE TABLE CONSENTS (
    ID VARCHAR2(255) PRIMARY KEY,
    CONTENT VARCHAR2(2000),
    IS_REQUIRED NUMBER(1)
);

CREATE TABLE USER_CONSENT_LOG (
    ID VARCHAR2(255) PRIMARY KEY,
    USER_ACCOUNT_ID VARCHAR2(255) NOT NULL,
    CONSENT_ID VARCHAR2(255) NOT NULL,
    CONSENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_UCL_USER FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
    CONSTRAINT FK_UCL_CONSENT FOREIGN KEY (CONSENT_ID) REFERENCES CONSENTS(ID)
);