package edu.pk.jawolh.erecepta.visitservice.model;

public enum Specialization {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    NEUROLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIOLOGY,
    SURGERY,
    UROLOGY,
    GYNECOLOGY,
    OBSTETRICS,
    FAMILY_MEDICINE,
    INTERNAL_MEDICINE,
    EMERGENCY_MEDICINE
}

